POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlciIsImlkIjoiNjU5ZjIwMDJkZDRkNDIxOGQzZmE2ZWM2IiwiaWF0IjoxNzA0OTY4Njg5LCJleHAiOjE3MDQ5NzIyODl9.q1TKjonhwkeMl7HIoj46z9ivysHAjkPkn0SDyvb_PF4

{
    "title": "Pers Book 10", 
    "author": "Developer41441",
    "url": "www.FSO34142.org",
    "likes": "111341"
}